configs:
  unpush_config:
    file: ./config.yaml

services:
  unpush:
    image: ghcr.io/tonyo/unpush:latest
    volumes:
      # unpush needs access to the Uncloud socket (/run/uncloud/uncloud.sock);
      # We are mounting the entire directory because of https://github.com/psviderski/uncloud/issues/404 
      - /run/uncloud/:/run/uncloud/
      - /var/run/docker.sock:/var/run/docker.sock   # required for repo mode builds
    configs:
      - source: unpush_config
        target: /deploy/config.yaml
    ports:
      - target: 8080
        published: 8080
    restart: always
